# -*- coding: utf-8 -*-
"""
Created on Fri Aug 23 21:57:49 2019

@author: luisf
"""

import pandas as pd
from copy import deepcopy

########################################################################################################
#sce = 'BAU'
sce = 'SR15'

model = 'Land'

if model == 'Land':

    #filename_orig = './2_Parameters/Integration_Parameters_'+ sce + '_WIDE.csv'
    filename_orig = './data_land_SR15_Output.csv'
    #filename_orig = './4_Results/data_water_Output.csv'
    #filename_orig = './4_Results/data_integration_Output.csv'
    #filename_orig = './2_Parameters/Integration_Parameters_BAU_WIDE.csv'
    #filename_orig = 'C:\Users\Administrador\Automatizacion\Suelo\2_Model\SR15\data_land_SR15_Output.csv'
    
    df = pd.read_csv(filename_orig)
    dfa = deepcopy( df )
    
    #Technologies
    #Land
    dfa['Technology'] = dfa['Technology'].replace({'BACKSTOP':'L_Backup for land system',
	'CRAREADESTASP':'L_Protected areas',
	'CRAREASERVIECOS':'L_Ecosystemic services',
	'CRCOBAGUA':'L_Land covered by water',
	'CRCOBCULT':'L_Crops',
	'CRCOBDESN':'L_Bare land',
	'CRCOBERBOS':'L_Forest',
	'CRCOBPAST':'L_Grassland',
	'CRCOBURB':'L_Urban areas',
	'CRCONSTCOMER':'L_Land for commercial construction',
	'CRCONSTINDUS':'L_Land for industrial construction',
	'CRCONSTRESIND':'L_Land for residential construction',
	'CRCONSTTRANS':'L_Land for transport infraestructure',
	'CRCONSUACEITE':'L_Palm oil demand',
	'CRCONSUARROZGR':'L_Rice demand',
	'CRCONSUAZUCAR':'L_Sugar demand',
	'CRCONSUBAGAZO':'L_Bagasse demand',
	'CRCONSUBANA':'L_Banana demand',
	'CRCONSUCAFEORO':'L_Coffee demand',
	'CRCONSUCAR_AVIC':'L_Chicken meat demand',
	'CRCONSUCAR_PORC':'L_Pork demand',
	'CRCONSUCAR_VACU':'L_Beef demand',
	'CRCONSUHUEVO':'L_Eggs demand',
	'CRCONSULECHE':'L_Milk demand',
	'CRCONSUMELA':'L_Molasses demand',
	'CRCONSUPINA':'L_Pineapple demand',
	'CREXPORTACEITE':'L_Palm oil exports',
	'CREXPORTARROZGR':'L_Rice exports',
	'CREXPORTAZUCAR':'L_Sugar exports',
	'CREXPORTBANA':'L_Banana exports',
	'CREXPORTCAFEORO':'L_Coffee exports',
	'CREXPORTCAR_AVIC':'L_Chicken meat exports',
	'CREXPORTCAR_PORC':'L_Pork meat exports',
	'CREXPORTCAR_VACU':'L_Beef exports',
	'CREXPORTHUEVO':'L_Eggs exports',
	'CREXPORTLECHE':'L_Milk exports',
	'CREXPORTMELA':'L_Molasses exports',
	'CREXPORTPINA':'L_Pineapple exports',
	'CRIMPORTACEITE':'L_Palm oil imports',
	'CRIMPORTARROZGR':'L_Rice imports',
	'CRIMPORTAZUCAR':'L_Sugar imports',
	'CRIMPORTBANA':'L_Banana imports',
	'CRIMPORTCAFEORO':'L_Coffee imports',
	'CRIMPORTCAR_AVIC':'L_Chicken meat imports',
	'CRIMPORTCAR_PORC':'L_Pork meat imports',
	'CRIMPORTCAR_VACU':'L_Beef imports',
	'CRIMPORTHUEVO':'L_Eggs imports',
	'CRIMPORTLECHE':'L_Milk imports',
	'CRIMPORTMELA':'L_Molasses imports',
	'CRIMPORTPINA':'L_Pineapple imports',
	'CRPROCEAZUCAR':'L_Sugar production',
	'CRPROCEPALMA':'L_Oil palm production',
	'CRPRODARROZ':'L_Rice production',
	'CRPRODARROZ_N':'L_Rice production (new)',
	'CRPRODBANA':'L_Banana production',
	'CRPRODBANA_N':'L_Banana production (new)',
	'CRPRODCAF':'L_Coffee production',
	'CRPRODCAF_N':'L_Coffee production (new)',
	'CRPRODCANA':'L_Sugarcane production',
	'CRPRODCANA_N':'L_Sugarcane production (new)',
	'CRPRODCARN_Avic':'L_Chicken meat production',
	'CRPRODCARN_Avic_N':'L_Chicken meat production (new)',
	'CRPRODCARN_Porc':'L_Pork meat production',
	'CRPRODCARN_Porc_N':'L_Pork meat production (new)',
	'CRPRODCARN_Vacu':'L_Beef production',
	'CRPRODCARN_Vacu_N':'L_Beef production (new)',
	'CRPRODHUEV':'L_Eggs production',
	'CRPRODHUEV_N':'L_Eggs production (new)',
	'CRPRODLECH':'L_Milk production',
	'CRPRODLECHE_N':'L_Milk production (new)',
	'CRPRODMADE':'L_Wood production',
	'CRPRODOTRO':'L_Other agricultural products production',
	'CRPRODOTRO_N':'L_Other agricultural products production (new)',
	'CRPRODPALM':'L_Oil palm production',
	'CRPRODPALM_N':'L_Oil palm production (new)',
	'CRPRODPIN':'L_Pineapple production',
	'CRPRODPIN_N':'L_Pineapple production (new)',
	'CRSUELO': 'Land',
    'CRASP_ESTADO':'L_State protected areas',
    'CRASP_PRIVADO':'L_Private protected areas',
    'CRBOSQ_MADU_PRIV':'L_Mature private forest',
    'CRBOSQUE_SECUN':'L_Secondary forest',
    'CRPLANTA_FORESTAL':'L_Forest plantation',
    'CR_DRY_PRI_FOREST':'L_Dry Primary Forest',
    'CR_DRY_SEC_FOREST':'L_Dry Secondary Forest',
    'CR_MANGR_PRI_FOREST':'L_Mangroves Primary Forest',
    'CR_MANGR_SEC_FOREST':'L_Mangroves Secondary Forest',
    'CR_MOIST_PRI_FOREST':'L_Moist Primary Forest',
    'CR_MOIST_SEC_FOREST':'L_Moist Secondary Forest',
    'CR_PALM_PRI_FOREST':'L_Palm Primary Forest',
    'CR_PALM_SEC_FOREST':'L_Palm Secondary Forest',
    'CR_WET_PRI_FOREST':'L_Wet Primary Forest',
    'CR_WET_SEC_FOREST':'L_Wet Secondary Forest',
    'CRCOB_OTR_TIERRAS':'L_Other land covers',
    'CRCOB_SIN_INFO':'L_Land covers without information',
    'CRCOBHUMEDA':'L_Wetlands',
    
    #Water
    'CRSUELO':'Land',
    'BACKSTOPAGUA' : 'W_Backup water',
    'CRADEMAGROP':'W_Agricultural water demand',
    'CRADEMCOM':'W_Commercial water demand',
    'CRADEMIND':'W_Industrial water demand',
    'CRADEMRESID':'W_Residential water demand',
    'CRADEMTUR':'W_Turistic water demand',
    'CRCOBBOSQUE':'W_Forest',
    'CRCOBCULT':'L_Crops',
    'CRCOBOTROS':'W_Other land coverages',
    'CRENENERGIA':'W_Energy',
    'CRENPRECIP':'W_Precipitation',
    'CRENSUELO':'W_Land',
    'CREPOT':'W_Water purification',
    'CRERIEGO':'W_Irrigation',
    'CREXTHIDROELEC':'W_Water extraction for hydroelectricity',
    'CREXTSUB':'W_Underground water extraction',
	'CREXTSUBFUT':'W_Underground water extraction (new)',
    'CREXTSUP':'W_Superficial water extraction',
	'CREXTSUPFUT':'W_Superficial water extraction (new)',
	'CRPOTFUT':'W_Water purification (new)',
    'CRREDACUED':'W_Water distribution',
	'CRREDACUEDFUT':'W_Water distribution (new)',
    'CRRETSUB':'W_Underground water return',
    'CRRETSUP':'W_Superficial water return',
	'CRVSINTRAT':'W_Water without treatment',
	'CRVTRAT':'W_Water treatment',
	'CRVTRATFUT':'W_Water treatment (new)',
    'CRADEMCOHUMANO':'W_Water demand for human consumption',
    'CRADEMINDYSERV':'W_Water industrial and services demand',
    'CRRIEGOFUT':'W_Irrigation (new)',
    'CRVSINTRATCOHUMANO':'W_Water without treatment from human consumption',
    'CRVSINTRATINDYSERV':'W_Water without treatment from industries and services',
    'CRVTRATCOHUMANO':'W_Water treatment from human consumption',
    'CRVTRATINDYSERV':'W_Water treatment from industries and services',
    'CRECONSUB':'W_Underground concessions',
    'CRECONSUP':'W_Superficial concessions',
    'CRVTRATFUTCOHUMANO':'W_Water treatment from human consumption (new)',
    'CRVTRATFUTINDYSERV':'W_Water treatment from industries and services (new)',
    'CRALCURB':'W_Urban Severage',
    'CRALCURBFUT':'W_Urban Severage (new)',
    'CRPOZOSRUR':'W_Septic tank rural',
    'CRPOZOSRURFUT':'W_Septic tank rural (new)',
    'CRALCSINTRAT':'W_Urban Sewerage without treatment',
    'CR03CONSUPAGROP':'W_Concession for agriculture',
    'CR03CONSUP':'W_Concession for industries',
    'CRCOBCARROZ':'W_Rice crops',
    'CRCOBCBANANO':'W_Banana crops',
    'CRCOBCCAFE':'W_Coffee crops',
    'CRCOBCCANA':'W_Sugarcane crops',
    'CRCOBCOTROS':'W_Other crops',
    'CRCOBCPALMA':'W_Oil palm crops',
    'CRCOBCPINA':'W_Pineapple crops',
    'CRCONSUBAGROP':'W_Underground concessions for agriculture',
    'CRCONSUPAGROP':'W_Superficial concessions for agriculture',
    'CRADEMHIDROELECTRICIDAD':'W_Water demand for hydroelectricity',
    
    #Energy
    'BACKSTOP_PS':'E_Backup Power Systems',
    'BACKSTOP_TS':'E_Backup Transport Sector',
    'BLENDDSL':'E_Blend Diesel',
    'BLENDGAS':'E_Blend Gasoline',
    'DBIO_El':'E_Biomass for electricity',
    'DBIO_In':'E_Biomass for industry',
    'DCOK_In':'E_Coke for industry',
    'DDSL_Ag':'E_Diesel for agriculture',
    'DDSL_El':'E_Diesel for electricity',
    'DDSL_Eq':'E_Diesel for equipment',
    'DDSL_HF':'E_Diesel for heavy freight transport',
    'DDSL_In':'E_Diesel for industry',
    'DDSL_LF':'E_Diesel for light freigth transport',
    'DDSL_Pr':'E_Diesel for private transport',
    'DDSL_Pu':'E_Diesel for public transport',
    'DELE_Ag':'E_Electricity for agriculture',
    'DELE_Co':'E_Electricity for commerce',
    'DELE_HF':'E_Electricity for heavy freight transport',
    'DELE_In':'E_Electricity for industry',
    'DELE_LF':'E_Electricity for light freigth transport',
    'DELE_Pb':'E_Electricity for public service',
    'DELE_Pr':'E_Electricity for Private Transport',
    'DELE_Pu':'E_Electricity for Public Transport',
    'DELE_Re':'E_Electricity for residencial',
    'DFOI_El':'E_Fuel Oil for Electricity',
    'DFOI_in':'E_Fuel Oil for Industry',
    'DFWO_Co':'E_Wood for commerce',
    'DFWO_In':'E_Wood for industry',
    'DFWO_Re':'E_Wood for residential',
    'DGSL_LF':'E_Gasoline for light freigth transport',
    'DGSL_Pr':'E_Gasoline for private transport',
    'DGSL_Pu':'E_Gasoline for public transport',
    'DHYD_HF':'E_Hydrogen for heavy freight transport',
    'DHYD_Pu':'E_Hydrogen for heavy public transport',
    'DIST_FOI':'E_Distribution of Fuel Oil',
    'DIST_FWO':'E_Distribution of Firewood',
    'DIST_JFUEL':'E_Distribution of Jet Fuel',
    'DIST_PCO':'E_Distribution of Petroleum Coke',
    'DIST_DSL':'E_Distribution Diesel',
    'DIST_GSL':'E_Distribution Gasoline',
    'DIST_HYD':'E_Distribution Hydrogen',
    'DIST_LPG':'E_Distribution LPG',
    'DIST_NG':'E_Distribution Natural Gas',
    'DJEFU_Ai':'E_Jet fuel air craft',
    'DLPG_Co':'E_LPG for commerce',
    'DLPG_HF':'E_LPG for heavy freight transport',
    'DLPG_In':'E_LPG for industry',
    'DLPG_LF':'E_LPG for light freight transport',
    'DLPG_Pr':'E_LPG for private transport',
    'DLPG_Pu':'E_LPG for public transport',
    'DLPG_Re':'E_LPG for residential',
    'DTRFF_hf':'E_Transport distribution demand fossil fuel heavy cargo',
    'DTRFF_lf':'E_Transport distribution demand fossil fuel light cargo',
    'DTRFF_pr':'E_Transport distribution demand fossil fuel private',
    'DTRFF_pu':'E_Transport distribution demand fossil fuel public',
    'DTRFF_rs':'E_Transport distribution demand fossil fuel ride sharing',
    'DTRLC_hf':'E_Transport distribution demand Low carbon heavy cargo',
    'DTRLC_lf':'E_Transport distribution demand Low carbon light cargo',
    'DTRLC_pr':'E_Transport distribution demand Low carbon private',
    'DTRLC_pu':'E_Transport distribution demand Low carbon public',
    'DTRLC_rs':'E_Transport distribution demand Low carbon  ride sharing',
    'DTRNM_Bk':'E_Transport distribution demand Bikes',
    'DTRNM_Wk':'E_Transport distribution demand Walks',
    'EDDISTAGR':'E_Electric Power Distribution for Agriculture',
    'EDDISTCOM':'E_Electric Power Distribution for Commercial',
    'EDDISTIND':'E_Electric Power Distribution for Industry',
    'EDDISTPUB':'E_Electric Power Distribution for Public',
    'EDDISTRES':'E_Electric Power Distribution for Residential',
    'EDEBIOIND':'E_Biomass Distribution  Industry',
    'EDEDSLAGR':'E_Diesel Distribution  Agriculture',
    'EDEDSLIND':'E_Diesel Distribution  Industry',
    'EDEFOIND':'E_Fuel Oil Distribution  Industry',
    'EDEFWCOM':'E_Firewood Distribution  Commercial',
    'EDEFWIND':'E_Firewood Distribution  Industry',
    'EDEFWRES':'E_Firewood Distribution  Residential',
    'EDEJFUAIR':'E_Jet fuel oil Distribution air',
    'EDELGPCOM':'E_LGP Distribution  Commercial',
    'EDELPGIND':'E_LPG Distribution  Industry',
    'EDELPGRES':'E_LPG Distribution  Residential',
    'EDEPCIND':'E_Petroleum Coke Distribution  Industry',
    'ESIMPBIODSL':'E_Importing biodiesel',
    'ESIMPDSL':'E_Importing Diesel',
    'ESIMPETHAN':'E_Importing ethanol',
    'ESIMPGAS':'E_Importing Gasoline',
    'ESIMPJEFU':'E_Importing Jet Fuel',
    'ESIMPLPG':'E_Importing LPG',
    'ESIMPNG':'E_Importing Natural Gas',
    'ESIMPOIFU':'E_Importing Oil Fuel',
    'ESIMPPCO':'E_Importing Petroleum Coke',
    'ESPROBIODSL':'E_Production biodiesel',
    'ESPROBIOGAS':'E_Production biogas',
    'ESPROETHAN':'E_Production ethanol',
    'ESRNBIO':'E_Biomass Resources',
    'ESRNFW':'E_Fire wood Resources',
    'ESRNGEO':'E_Renewable Resource Geothermal',
    'ESRNSUN':'E_Renewable Resource Solar',
    'ESRNWAT':'E_Renewable Resource Water',
    'ESRNWND':'E_Renewable Resource Wind',
    'ESROMBIO':'E_Organic Material Resources',
    'PPBIO001':'E_Biomass Power Plant (existing)',
    'PPBIO002':'E_Biomass Power Plant (new)',
    'PPDSL001':'E_Diesel Power Plant (existing)',
    'PPDSL002':'E_Diesel Power Plant (new)',
    'PPFOB001':'E_Oil Power Plant (existing)',
    'PPFOB002':'E_Oil Power Plant (new)',
    'PPGEO001':'E_Geothermal Power Plant (existing)',
    'PPGEO002':'E_Geothermal Power Plant (new)',
    'PPHDAM001':'E_Hydro Dam Power Plant (existing)',
    'PPHDAM002':'E_Hydro Dam Power Plant (new)',
    'PPHROR001':'E_Hydro Run of River Power Plant (existing)',
    'PPHROR002':'E_Hydro Run of River Power Plant (new)',
    'PPPVD001':'E_Photovoltaic Power Plant Distribution (existing)',
    'PPPVD002':'E_Photovoltaic Power Plant Distribution (new)',
    'PPPVT001':'E_Photovoltaic Power Plant Transmission (existing)',
    'PPPVT002':'E_Photovoltaic Power Plant Transmission (new)',
    'PPWND001':'E_Wind Power Plant Distribution (existing)',
    'PPWND002':'E_Wind Power Plant Distribution (new)',
    'PPWNT001':'E_Wind Power Plant Transmission  (existing)',
    'PPWNT002':'E_Wind Power Plant Transmission (new)',
    'PROD_HYD_CH4':'E_Production hydrogen CH4',
    'PROD_HYD_H20':'E_Production hydrogen H2O',
    'TDDIST01':'E_Electricity Distribution (existing)',
    'TDDIST02':'E_Electricity Distribution (new)',
    'TDMEREL01':'E_Imports of electricity',
    'TDMEREL02':'E_Exports of electricity',
    'TDTRANS01':'E_Electricity Transmission (existing)',
    'TDTRANS02':'E_Electricity Transmission (new)',
    'TI_BW_01':'E_Bikeway (existing)',
    'TI_BW_02':'E_Bikeway (new)',
    'TI_RaRo_01':'E_Railroad (existing)',
    'TI_RaRo_02':'E_Railroad (new)',
    'TI_RoNet_01':'E_Road network (existing)',
    'TI_RoNet_02':'E_Road network (new)',
    'TI_SW_01':'E_Sidewalk (existing)',
    'TI_SW_02':'E_Sidewalk (new)',
    'TRANOMOTBike':'E_No motorized transport bikes',
    'TRANOMOTWalk':'E_No motorized transport Walk',
    'TRBUSDSL01':'E_Bus Diesel (existing)',
    'TRBUSDSL02':'E_Bus Diesel (new)',
    'TRBUSELC02':'E_Bus Electric (new)',
    'TRBUSHYBD02':'E_Bus Hybrid Electric-Diesel (new)',
    'TRBUSHYD02':'E_Bus Hydrogen (new)',
    'TRBUSLPG02':'E_Bus LPG (new)',
    'TRFWDDSL01':'E_Four-Wheel-Drive (existing)',
    'TRFWDDSL02':'E_Four-Wheel-Drive Diesel (new)',
    'TRFWDELE02':'E_Four-Wheel-Drive Electric (new)',
    'TRFWDGAS01':'E_Four-Wheel-Drive Gasoline (existing)',
    'TRFWDGAS02':'E_Four-Wheel-Drive Gasoline (new)',
    'TRFWDHYBD02':'E_Four-Wheel-Drive Hybrid Electric-Diesel (new)',
    'TRFWDLPG01':'E_Four-Wheel-Drive LPG (existing)',
    'TRFWDLPG02':'E_Four-Wheel-Drive LPG (new)',
    'TRFWDPHYBD02':'E_Four-Wheel-Drive Plug-in Hybrid Electric-Diesel(new)',
    'TRLDDSL01':'E_Light Duty Diesel (existing)',
    'TRLDDSL02':'E_Light Duty Diesel (new)',
    'TRLDELE02':'E_Light Duty Electric (new)',
    'TRLDGAS01':'E_Light Duty Gasoline (existing)',
    'TRLDGAS02':'E_Light Duty Gasoline (new)',
    'TRLDHYBG02':'E_Light Hybrid Electric-Gasoline (new)',
    'TRLDPHYBG02':'E_Light Plug-in Hybrid Electric-Gasoline  (new)',
    'TRMBUSDSL01':'E_Microbus Diesel (existing)',
    'TRMBUSDSL02':'E_Microbus Diesel (new)',
    'TRMBUSELE02':'E_Microbus Electric (new)',
    'TRMBUSHYBD02':'E_Microbus Hybrid Electric-Diesel (new)',
    'TRMBUSHYD02':'E_Microbus Hydrogen (new)',
    'TRMBUSLPG02':'E_Microbus LPG (new)',
    'TRMIVDSL01':'E_Minivan Diesel (existing)',
    'TRMIVDSL02':'E_Minivan Diesel (new)',
    'TRMIVELE02':'E_Minivan Electric (new)',
    'TRMIVGAS01':'E_Minivan Gasoline (existing)',
    'TRMIVGAS02':'E_Minivan Gasoline (new)',
    'TRMIVHYBD02':'E_Minivan Hybrid Electric-Diesel (new)',
    'TRMIVHYBG02':'E_Minivan Hybrid Electric-Gasoline (new)',
    'TRMIVLPG01':'E_Minivan LPG (existing)',
    'TRMIVLPG02':'E_Minivan LPG (new)',
    'TRMOTELC02':'E_Motorcycle electric (new)',
    'TRMOTGAS01':'E_Motorcycle Gasoline (existing)',
    'TRMOTGAS02':'E_Motorcycle Gasoline (new)',
    'TRTAXDSL01':'E_Taxi Diesel (existing)',
    'TRTAXDSL02':'E_Taxi Diesel (new)',
    'TRTAXELC02':'E_Taxi Electric (new)',
    'TRTAXGAS01':'E_Taxi Gasoline (existing)',
    'TRTAXGAS02':'E_Taxi Gasoline (new)',
    'TRTAXHYBD02':'E_Taxi Hybrid Electric-Diesel (new)',
    'TRTAXHYBG02':'E_Taxi Hybrid Electric-Gasoline (new)',
    'TRTAXLPG01':'E_Taxi LPG (existing)',
    'TRTAXLPG02':'E_Taxi LPG (new)',
    'TRXTRAIELEFRE02':'E_Train Electric for Freight (new)',
    'TRXTRAINDSL01':'E_Train Diesel (existing)',
    'TRXTRAINDSL02':'E_Train Diesel (new)',
    'TRXTRAINELC02':'E_Train Electric (new)',
    'TRYLFDSL01':'E_Mini Trucks (existing)',
    'TRYLFDSL02':'E_Mini Trucks Diesel (new)',
    'TRYLFELE02':'E_Mini Trucks Electric (new)',
    'TRYLFGAS01':'E_Mini Trucks Gasoline (existing)',
    'TRYLFGAS02':'E_Mini Trucks Gasoline (new)',
    'TRYLFHYBD02':'E_Mini Trucks Hybrid Electric-Diesel (new)',
    'TRYLFHYBG02':'E_Mini Trucks Electric-Gasoline (new)',
    'TRYLFLPG01':'E_Mini Trucks LPG (existing)',
    'TRYLFLPG02':'E_Mini Trucks LPG (new)',
    'TRYTKDSL01':'E_Trucks Diesel (existing)',
    'TRYTKDSL02':'E_Trucks Diesel (new)',
    'TRYTKELC02':'E_Trucks Electric (new)',
    'TRYTKHYBD02':'E_Trucks Hybrid Electric-Diesel (new)',
    'TRYTKHYD02':'E_Trucks Hydrogen (new)',
    'TRYTKLPG02':'E_Trucks LPG (new)',
    'TRZAIR001':'E_Air (existing)',
    'TRZSEQ001':'E_Special Equipment & Sea (existing)',
    'Techs_4WD':'E_Four Wheel Drive',
    'Techs_Buses':'E_Bus',
    'Techs_LD':'E_Light Duty',
    'Techs_Microbuses':'E_Minbus',
    'Techs_Minivan':'E_Minivan',
    'Techs_Motos':'E_Motorcycles',
    'Techs_Taxis':'E_Taxis',
    'Techs_Trains':'E_Rail'})
    
    #Fuels
    #Water
    dfa['Fuel'] = dfa['Fuel'].replace({'CR00ENERGIA':'W_Energy',
	'CR00PRECIP':'W_Precipitation',
	'CR00SUELO':'W_Land',
	'CR01AGUASUB':'W_Underground water',
	'CR01AGUASUP':'W_Superficial water',
	'CR01EVAPOT':'W_Evapotranspiration',
	'CR02EXTHIDROELEC':'W_Water extraction for hydroelectricity',
	'CR02EXTSUB':'W_Underground extraction',
	'CR02EXTSUP':'W_Superficial extraction',
	'CR03AGUAPOT':'W_Drinking water',
	'CR03AGUARIEGO':'W_Water for irrigation',
	'CR03PERPRIEGO':'W_Irrigation losses',
	'CR04AGUADIST':'W_Water for distribution',
	'CR04PERPDIST':'W_Distribution losses',
	'CR05DEMAGROP':'W_Demand for agriculture',
	'CR05DEMCOM':'W_Commercial demand',
	'CR05DEMIND':'W_Industrial demand',
	'CR05DEMRESID':'W_Residential demand',
	'CR05DEMTUR':'W_Tourisim demand',
	'CR06VERTIDOS':'W_Residual waters',
    'CR05DEMCOHUMANO':'W_Water demand for human consumption',
    'CR05DEMINDYSERV':'W_Water industrial and services demand',
    'CR06VERTCOHUMANO':'W_Waste water from human consumtion',
    'CR06VERTINDYSERV':'W_Waste water from industries and services',
    'CR06RESTR':'W_Collected wastewater',
    'CR05DEMHIDROELECTRICIDAD':'W_Water demand for hydroelectricity',
    'CR03CONSUB':'W_Underground concessions for industry and services',
    'CR03CONSUBAGROP':'W_Underground concessions for agriculture',
    'CR03CONSUPAGROP':'W_Superficial concessions for agriculture',
    'CR03CONSUP':'W_Superficial concessions for industry and services',
    
    #Land
    'CR01SUELO':'L_Land',
	'CR02BOSQUE':'L_Forest',
	'CR02CUERPAGUA':'L_Land covered by water',
	'CR02CULTIVOS':'L_Crops',
	'CR02DESNU':'L_Bared land',
	'CR02PASTOS':'L_Grassland',
	'CR02URBANO':'L_Urban areas',
	'CR03ARROZ':'L_Rice crops',
	'CR03BANANO':'L_Banana crops',
	'CR03CAFE':'L_Coffee crops',
	'CR03CANA':'L_Sugarcane crops',
	'CR03CARNE_Avic':'L_Land for chiken meat production',
	'CR03CARNE_Porc':'L_Land for pork meat production',
	'CR03CARNE_Vacu':'L_Land for beef production',
	'CR03HUEVOS':'L_Land for eggs production',
	'CR03LECHE':'L_Land for milk production',
	'CR03OTROS':'L_Land for other agricultural products prooduction',
	'CR03PALMA':'L_Land for oil palm production',
	'CR03PINA':'L_Land for pineapple production',
	'CR04DEMCOMER':'L_Land demand for commercial construction',
	'CR04DEMINDUST':'L_Land demand for industrial construcion',
	'CR04DEMRESIDE':'L_Land demand for residencial construction',
	'CR04DEMSILVI':'L_Wood demand',
	'CR04DEMTRANSP':'L_Land demand for transfort infraestructure',
	'CR05ASP':'L_Protected areas',
	'CR05SERVICECOS':'L_Ecosystemic services',
	'CR06ACEITE':'L_Palm oil production',
	'CR06AZUCAR':'L_Sugar production',
	'CR06BAGAZO':'L_Bagasse production',
	'CR06MELAZA':'L_Molasses production',
	'CR07DEMAACEITE':'L_Palm oil demand',
	'CR07DEMAARROZ':'L_Rice demand',
	'CR07DEMAAZUCAR':'L_Sugar demand',
	'CR07DEMABAGAZO':'L_Bagasse demand',
	'CR07DEMABANANO':'L_Banana demand',
	'CR07DEMACAFORO':'L_Coffe demand',
	'CR07DEMAMELA':'L_Molasses demand',
	'CR07DEMAPINA':'L_Pineapple demand',
	'CR07EXPOACEITE':'L_Palm oil exports',
	'CR07EXPOARROZ':'L_Rice exports',
	'CR07EXPOAZUCAR':'L_Sugar exports',
	'CR07EXPOBANANO':'L_Banana exports',
	'CR07EXPOCAFORO':'L_Coffee exports',
	'CR07EXPOMELA':'L_Molasses exports',
	'CR07EXPOPINA':'L_Pineapple exportes',
	'CR08DEMACAR_AVIC':'L_Chiken meat demand',
	'CR08DEMACAR_PORC':'L_Pork meat demand',
	'CR08DEMACAR_VACU':'L_Beef demand',
	'CR08DEMAHUEVO':'L_Eggs demand',
	'CR08DEMALECHE':'L_Milk demand',
	'CR08EXPOCAR_AVIC':'L_Chicken meat exports',
	'CR08EXPOCAR_PORC':'L_Pork meat demand',
	'CR08EXPOCAR_VACU':'L_Beef exports',
	'CR08EXPOHUEVO':'L_Eggs exports',
	'CR08EXPOLECHE':'L_Milk exports',
    'CR05ASP_ESTADO':'L_State protected areas',
    'CR05ASP_PRIVADO':'L_Private protected areas',
    'CR05BOSQ_MAD_PRIV':'L_Mature private forest',
    'CR05BOSQUE_SECUN':'L_Secondary forest',
    'CR05MADERA':'L_Wood demand',
    'CR02HUMEDALES':'L_Wetlands',
    'CR02OTR_TIERRAS':'L_Other land covers',
    'CR02SIN_INFO':'L_Covers without information',
    'CR05DRY_PRI_FOREST':'L_Dry Primary Forest',
    'CR05DRY_SEC_FOREST':'L_Dry Secondary Forest',
    'CR05MANGR_PRI_FOREST':'L_Mangroves Primary Forest',
    'CR05MANGR_SEC_FOREST':'L_Mangroves Secondary Forest',
    'CR05MOIST_PRI_FOREST':'L_Moist Primary Forest',
    'CR05MOIST_SEC_FOREST':'L_Moist Secondary Forest',
    'CR05PALM_PRI_FOREST':'L_Palm Primary Forest',
    'CR05PALM_SEC_FOREST':'L_Palm Secondary Forest',
    'CR05WET_PRI_FOREST':'L_Wet Primary Forest',
    'CR05WET_SEC_FOREST':'L_Wet Secondary Forest',

    #Energy
    'E0BIODSL':'E_Biodisel imported or produced',
    'E0DSL':'E_Diesel imported',
    'E0DSLBLEND':'E_Diesel and biodiseal blend',
    'E0ETHAN':'E_Ethanol  imported or produced',
    'E0GSL':'E_Gasoline imported',
    'E0GSLBLEND':'E_Gasoline and ethanol blend',
    'E0LPG':'E_LPG imported',
    'E0NATGAS':'E_Natural Gas imported',
    'E1BIO':'E_Biomass energy',
    'E1DSL':'E_Diesel',
    'E1FOI':'E_Fuel Oil',
    'E1FWO':'E_Firewood',
    'E1GAS':'E_Gasoline',
    'E1GEO':'E_Geothermal energy',
    'E1GSL':'E_Gasoline',
    'E1JEFU':'E_Jet Fuel',
    'E1LPG':'E_Liquid Petroleum Gas',
    'E1METH':'E_Methene',
    'E1PCO':'E_Petroleum coke',
    'E1SOL':'E_Solar energy',
    'E1WAT':'E_Hydraulic energy',
    'E1WIN':'E_Eolic Energy',
    'E2ELC01':'E_Electricity Supply by Plants',
    'E2HYD':'E_Hydrogen produced',
    'E3ELC02':'E_Electricity for Transmission',
    'E3ELC03':'E_Electricity for Distribution',
    'E3ELC04':'E_Electricity Exports',
    'E4ELC03AGR':'E_Agriculture  Electricity Demand',
    'E4ELC03COM':'E_Commercial Electricity Demand',
    'E4ELC03IND':'E_Industrial  Electricity Demand',
    'E4ELC03PUB':'E_Public  Electricity Demand',
    'E4ELC03RES':'E_Residential  Electricity Demand',
    'E5BIOIND':'E_Biomass  for Industry',
    'E5DSLAGR':'E_Diesel End Use Agriculture',
    'E5DSLIND':'E_Diesel End Use Industry',
    'E5FWCOM':'E_Firewood End Use Commercial',
    'E5FWIND':'E_Firewood End Use Industry',
    'E5FWRES':'E_Firewood End Use Residential',
    'E5LGPCOM':'E_LGP End Use Commercial',
    'E5LPGIND':'E_LPG End Use Industry',
    'E5LPGRES':'E_LPG End Use Residential',
    'E5OFIND':'E_Fuel Oil End Use Industry',
    'E5PCIND':'E_Petroleum Coke End Use Industry',
    'E6TDAIR':'E_Transport Demand Air',
    'E6TDFREHEA':'E_Transport Demand Freigth Heavy',
    'E6TDFRELIG':'E_Transport Demand Freigth Light',
    'E6TDPASPRIV':'E_Transport Demand Passenger Private',
    'E6TDPASSPUB':'E_Transport Demand Passenger Public',
    'E6TDSPE':'E_Transport Demand Special Equipment & Sea',
    'E6TRNOMOT':'E_Transport Demand Passenger No Motorize',
    'E6TRRIDSHA':'E_Transport Demand Passenger Ride Sharing',
    'E7BAG_In':'E_Baggase for Industry',
    'E7BIKEWAYS':'E_Bikeways infrastructure',
    'E7BIO_El':'E_Biomass for electricity',
    'E7BIO_In':'E_Biomass  for Industry',
    'E7COK_In':'E_Coke for Industry',
    'E7DSL_Ag':'E_Diesel for agriculture',
    'E7DSL_El':'E_Diesel for electricity',
    'E7DSL_Eq':'E_Diesel for special equipment',
    'E7DSL_HF':'E_Diesel for light heavy transport',
    'E7DSL_In':'E_Diesel for industry',
    'E7DSL_LF':'E_Diesel for light freight transport',
    'E7DSL_Pr':'E_Diesel for private transport',
    'E7DSL_Pu':'E_Diesel for public transport',
    'E7ELE_Ag':'E_Electricity for Agriculture',
    'E7ELE_Co':'E_Electricity for Commerce',
    'E7ELE_HF':'E_Electricity for heavy freight transport',
    'E7ELE_Ind':'E_Electricity for Industry',
    'E7ELE_LF':'E_Electricity for light freight transport',
    'E7ELE_Pb':'E_Electricity for public service',
    'E7ELE_Pr':'E_Electricity for private transport',
    'E7ELE_Pu':'E_Electricity for public transport',
    'E7ELE_Re':'E_Electricity for Commerce',
    'E7FOI_El':'E_Fuel oil for electricity',
    'E7FOI_In':'E_Fuel Oil for Industry',
    'E7FWO_Co':'E_Wood for commerce',
    'E7FWO_In':'E_Wood for industry',
    'E7FWO_Re':'E_Wood for residential',
    'E7GSL_LF':'E_Gasoline  for light freight transport',
    'E7GSL_Pr':'E_Gasoline for private transport',
    'E7GSL_Pu':'E_Gasoline for public transport',
    'E7HYD_HF':'E_Hydrogen for heavy freight transport',
    'E7HYD_Pu':'E_Hydrogen for public transport',
    'E7JFU_Ai':'E_Jet fuel for aircraft',
    'E7LPG_Co':'E_LPG for commerce',
    'E7LPG_HF':'E_LPG for heavy freight transport',
    'E7LPG_In':'E_LPG for industry',
    'E7LPG_LF':'E_LPG for light freight transport',
    'E7LPG_Pr':'E_LPG for private transport',
    'E7LPG_Pu':'E_LPG for public transport',
    'E7LPG_Re':'E_LPG for residential',
    'E8Fossil_HF':'E_E_Demand Fossil Fuel Heavy Freight',
    'E8Fossil_LF':'E_E_Demand Fossil Fuel Light Freight',
    'E8Fossil_pri':'E_E_Demand Fossil Fuel Private',
    'E8Fossil_pu':'E_E_Demand Fossil Fuel Public',
    'E8Fossil_RS':'E_E_Demand Fossil Fuel RideSharing',
    'E8LowCO2_HF':'E_E_Demand Low Carbon  Heavy Freight',
    'E8LowCO2_LF':'E_E_Demand Low Carbon  Light Freight',
    'E8LowCO2_pr':'E_E_Demand Low Carbon  Private',
    'E8LowCO2_pu':'E_Demand Low Carbon  Public',
    'E8LowCO2_RS':'E_Demand Low Carbon  RideSharing',
    'E8NoMotor_B':'E_Demand No motorize Bikes',
    'E8NoMotor_W':'E_Demand No motorize walk',
    'E9ELESTOR_HF':'E_Electricity storage for heavy freight',
    'E9ELESTOR_LF':'E_Electricity storage for light freight',
    'E9ELESTOR_Pr':'E_Electricity storage for private vehicles',
    'E9ELESTOR_Pu':'E_Electricity storage for public transport',
    'E9ELESTORAGE':'E_Electricity storage',
    'ETFREIGHT':'E_Cargo demand',
    'ETPASSENGER':'E_Passanger demand',
    'HYDROGEN':'E_Hydrogen',
    'TIBIKEWAYS':'E_Bikeways infrastructure',
    'TIRAILS':'E_Rails infrastructerestrucre',
    'TIROADS':'E_Roads infrastructure',
    'TISIDEWALKS':'E_Sidewalks infrastructure',
    'FPr_4WD':'E_Private Transport in Four Wheel Drive',
    'FPr_LightDuty':'E_Private Transport in Light Duty',
    'FPr_Minivan':'E_Private Transport in Minivan',
    'FPr_Moto':'E_Private Transport in Motorcycle',
    'FPu_Buses':'E_Public Transport in Buses',
    'FPu_Micros':'E_Public Transport in Minibus',
    'FPu_Taxis':'E_Public Transport in Taxi',
    'FPu_Train':'E_Transport in Rail',
    'FHF_Trucks':'E_Fuels_Grouping_Heavy_Freight',
    'FLF_PickUpTrucks':'E_Fuels_Grouping_Light_Freight'})
    
    #Emissiones
    #Land and water
    dfa['Emission'] = dfa['Emission'].replace({'CR_ABS':'L_Removals',
    'CRCH4':'LW_Methane',
    'CRCO2':'LW_Carbon Dioxide',
    'CRN20':'LW_Nitrous Oxide',
    'CRCO2_EQ_ESTIERCOL':'L_Eq carbon dioxide manure management',
    'CRCO2_EQ_FERMEN':'L_Eq carbon dioxide from enteric fermentation',
    'CRCO2_ABS_P_FOR':'L_Removals from forest plantaions',
    'CRCO2_CULTIVOS':'L_Emissions from crops',
    'SE_DRY_Forest':'L_Ecosystem services from dry forest',
    'SE_MANGRO_Forest':'L_Ecosystem servoces from Mangroves',
    'SE_PALM_Fosrest':'L_Ecosystem services from Palm Forest',
    'SE_WET_MOIST_Forest':'L_Ecosystem services from Moist Forest',
    #Energy
    'C02_Freight':'E_Carbon Dioxide Freight',
    'CO2_HeavyCargo':'E_Carbon Dioxide Heavy Cargo',
    'CO2_LightCargo':'E_Carbon Dioxide Light Cargo',
    'CO2_sources':'E_Carbon Dioxide Sources',
    'CO2_Transport':'E_Carbon Dioxide Transport', 
    #Water
    'CO2':'W_Emissions from waste water'})
    
    #dfa.to_csv ( './2_Parameters/Integration_Parameters_WIDE_CODED.csv', index = None, header=True)
    #dfa.to_csv ( './3_Visualization/Integration_Parameters_WIDE_CODED.csv', index = None, header=True)
    dfa.to_csv ( './data_land_Output_CODED.csv', index = None, header=True)
   #dfa.to_csv ( './4_Results/data_water_Output_CODED.csv', index = None, header=True)
    
    #dfa.to_csv ( './4_Results/data_integrated_Output_CODED.csv', index = None, header=True)
    
########################################################################################################